@startuml

SimpleArrayMap <|-- ArrayMap

class ArrayMap {
    mCollections : MapCollections<K, V>
}

class SimpleArrayMap {
   {static}-BASE_SIZE: int = 4
   {static}-CACHE_SIZE: int = 10
   {static}~mBaseCache: Object[]
   {static}~mTwiceBaseCache: Object[]
   
   ~mHashes : int[]
   ~mArray : Object[]
   ~mSize : int
   
   put(K key, V value): V
   keyAt(int index): K
   valueAt(int index): V
   setValueAt(int index, V value): V
   remove(Object key): V
   
   

}


@enduml

