@startuml

interface CharSequence
interface Spanned
interface Spannable

CharSequence <|-- Spanned
Spanned <|-- Spannable
Spannable <|.. SpannableStringBuilder
Spannable <|.. SpannableString




@enduml